set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:Tc"

set -g mouse on
set -sg escape-time 10
set -g history-limit 10000
set -g status-interval 1

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g status-position bottom

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind r source-file ~/.config/tmux/tmux.conf \; display-message "  Config reloaded!"

# Global status bar
set -g status-style "bg=#161616,fg=#f2f4f8"
set -g status-left-length 120
set -g status-right-length 200

# Pane borders
set -g pane-border-style "fg=#393939"
set -g pane-active-border-style "fg=#78a9ff"

# Message style
set -g message-style "bg=#262626,fg=#78a9ff,bold"

# Copy mode highlight
set -g mode-style "bg=#be95ff,fg=#161616,bold"

# Left: session + current path
set -g status-left "\
#[fg=#161616,bg=#78a9ff,bold] 󰓩 #S \
#[fg=#78a9ff,bg=#262626]\
#[fg=#dde1e7,bg=#262626]  #{b:pane_current_path} \
#[fg=#262626,bg=#161616] "

# Window tabs
set -g window-status-separator ""

set -g window-status-format "\
#[fg=#697077,bg=#161616]  #I 󰁔 #W  "

set -g window-status-current-format "\
#[fg=#161616,bg=#be95ff]\
#[fg=#161616,bg=#be95ff,bold]  #I 󰁔 #W  \
#[fg=#be95ff,bg=#161616]"

set -g window-status-activity-style "bg=#161616,fg=#f1c21b,bold"
set -g window-status-bell-style "bg=#161616,fg=#fa4d56,bold"

# Right: hostname | date | time
set -g status-right "\
#[fg=#262626,bg=#161616]\
#[fg=#dde1e7,bg=#262626]  #h \
#[fg=#393939,bg=#262626]\
#[fg=#f2f4f8,bg=#393939] 󰃰 %Y-%m-%d \
#[fg=#78a9ff,bg=#393939]\
#[fg=#161616,bg=#78a9ff,bold]  %H:%M:%S "


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'wfxr/tmux-fzf-url'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
